# Упражнение на нейронные сети/Keras

Задание - исследовать метрики в зависимости от архитектуры нейронной сети.  
В случае задания regression использовать выборку load_boston(MSE)  
В случае задания binary использовать выборку load_breast_cancer(accuary)  
В случае задания multiclass использовать выборку load_iris(accuary)  

Выборку разделить на train/test. Исследовать значение метрики в зависимости от:  
1. Количества Dense слоев.
2. Количества нейрнов в слоях
3. Промежуточных функций активаций   

Можете поиграться с другими слоями Keras(например Dropout)

Очень важно правильно настроить optimizer и выбрать lr, который обеспечит сходимость!

Активации Keras: https://keras.io/activations/  
Подробнее про оптимайзеры: http://ruder.io/optimizing-gradient-descent/  


Статьи:  
https://machinelearningmastery.com/tutorial-first-neural-network-python-keras/  
https://machinelearningmastery.com/use-keras-deep-learning-models-scikit-learn-python/  
https://machinelearningmastery.com/multi-class-classification-tutorial-keras-deep-learning-library/   

In [1]:
from sklearn.datasets import load_boston, load_breast_cancer, load_iris
# boston - regression
# breast - binary
# iris - multiclass
# Create your first MLP in Keras
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.optimizers import SGD, Adam
from keras.callbacks import TensorBoard

import numpy as np

from sklearn.model_selection import train_test_split

from keras.utils import np_utils

np.random.seed(7)

Using TensorFlow backend.


In [2]:
def test(model, optimizer, loss, metrics, epochs, batch_size):
    # Compile model
    model.compile(loss=loss, optimizer=optimizer, metrics=metrics)
    # Fit the model
    model.fit(X_train, y_train, epochs=epochs, batch_size=batch_size)
    # evaluate the model
    scores = model.evaluate(X_test, y_test)
    for metric, score in zip(model.metrics_names, scores):
        print(f'{metric}: {score}')

## Бинарная классификация

In [3]:
data = load_breast_cancer()
X = data.data
y = data.target
print(y[:10])
print(y.mean())

[0 0 0 0 0 0 0 0 0 0]
0.6274165202108963


In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, shuffle=True, random_state=7)

In [5]:
test(
    model = Sequential([
        Dense(12, input_dim=X.shape[1], activation='relu'),
        Dense(8, activation='relu'),
        # для бинарной классификации на выходе 1 нейрон и сигмоид
        Dense(1, activation='sigmoid')
    ]),
    optimizer = Adam(lr=0.00001),
    # Нужно выбрать loss = binary_crossentropy для бинарной классификации
    loss = 'binary_crossentropy',
    metrics=['accuracy'],
    epochs=150,
    batch_size=10
)

Epoch 1/150
455/455 [==============================] - 0s 302us/step - loss: 33.3941 - accuracy: 0.3736
Epoch 2/150
455/455 [==============================] - 0s 107us/step - loss: 32.9061 - accuracy: 0.3736
Epoch 3/150
455/455 [==============================] - 0s 158us/step - loss: 32.4184 - accuracy: 0.3736
Epoch 4/150
455/455 [==============================] - 0s 147us/step - loss: 31.9292 - accuracy: 0.3736
Epoch 5/150
455/455 [==============================] - 0s 159us/step - loss: 31.4493 - accuracy: 0.3736
Epoch 6/150
455/455 [==============================] - 0s 159us/step - loss: 30.9727 - accuracy: 0.3736
Epoch 7/150
455/455 [==============================] - 0s 155us/step - loss: 30.4958 - accuracy: 0.3736
Epoch 8/150
455/455 [==============================] - 0s 178us/step - loss: 30.0221 - accuracy: 0.3736
Epoch 9/150
455/455 [==============================] - 0s 164us/step - loss: 29.5520 - accuracy: 0.3736
Epoch 10/150
455/455 [==============================] - 0s 163us

In [6]:
test(
    model = Sequential([
        Dense(X.shape[1], input_dim=X.shape[1], activation='relu'),
        Dense(X.shape[1], activation='relu'),
        Dense(X.shape[1], activation='relu'),
        Dense(X.shape[1], activation='relu'),
        Dense(1, activation='sigmoid')
    ]),
    optimizer = Adam(lr=0.00001),
    loss = 'binary_crossentropy',
    metrics=['accuracy'],
    epochs=150,
    batch_size=10
)

Epoch 1/150
455/455 [==============================] - 0s 437us/step - loss: 15.7990 - accuracy: 0.3736
Epoch 2/150
455/455 [==============================] - 0s 194us/step - loss: 14.2192 - accuracy: 0.3736
Epoch 3/150
455/455 [==============================] - 0s 188us/step - loss: 12.6426 - accuracy: 0.3736
Epoch 4/150
455/455 [==============================] - 0s 165us/step - loss: 11.0494 - accuracy: 0.3736
Epoch 5/150
455/455 [==============================] - 0s 179us/step - loss: 9.4503 - accuracy: 0.3736
Epoch 6/150
455/455 [==============================] - 0s 195us/step - loss: 7.8134 - accuracy: 0.3736
Epoch 7/150
455/455 [==============================] - 0s 177us/step - loss: 6.1139 - accuracy: 0.3736
Epoch 8/150
455/455 [==============================] - 0s 175us/step - loss: 4.3302 - accuracy: 0.3736
Epoch 9/150
455/455 [==============================] - 0s 222us/step - loss: 2.5266 - accuracy: 0.3736
Epoch 10/150
455/455 [==============================] - 0s 180us/step

In [7]:
test(
    model = Sequential([
        Dense(X.shape[1], input_dim=X.shape[1], activation='relu'),
        Dense(X.shape[1], activation='relu'),
        Dense(X.shape[1], activation='relu'),
        Dense(1, activation='sigmoid')
    ]),
    optimizer = Adam(lr=0.00001),
    loss = 'binary_crossentropy',
    metrics=['accuracy'],
    epochs=150,
    batch_size=10
)

Epoch 1/150
455/455 [==============================] - 0s 377us/step - loss: 0.5151 - accuracy: 0.7846
Epoch 2/150
455/455 [==============================] - 0s 174us/step - loss: 0.4913 - accuracy: 0.8176
Epoch 3/150
455/455 [==============================] - 0s 150us/step - loss: 0.4671 - accuracy: 0.8352
Epoch 4/150
455/455 [==============================] - 0s 154us/step - loss: 0.4518 - accuracy: 0.8505
Epoch 5/150
455/455 [==============================] - 0s 182us/step - loss: 0.4422 - accuracy: 0.8505
Epoch 6/150
455/455 [==============================] - 0s 195us/step - loss: 0.4315 - accuracy: 0.8681
Epoch 7/150
455/455 [==============================] - 0s 185us/step - loss: 0.4177 - accuracy: 0.8571
Epoch 8/150
455/455 [==============================] - 0s 162us/step - loss: 0.4198 - accuracy: 0.8681
Epoch 9/150
455/455 [==============================] - 0s 162us/step - loss: 0.4000 - accuracy: 0.8857
Epoch 10/150
455/455 [==============================] - 0s 177us/step - l

In [8]:
print(X.shape[1])

30


In [9]:
test(
    model = Sequential([
        Dense(X.shape[1], input_dim=X.shape[1], activation='relu'),
        Dense(15, activation='relu'),
        Dense(10, activation='relu'),
        Dense(5, activation='relu'),
        Dense(1, activation='sigmoid')
    ]),
    optimizer = Adam(lr=0.00001),
    loss = 'binary_crossentropy',
    metrics=['accuracy'],
    epochs=150,
    batch_size=10
)

Epoch 1/150
455/455 [==============================] - 0s 408us/step - loss: 41.1896 - accuracy: 0.3736
Epoch 2/150
455/455 [==============================] - 0s 149us/step - loss: 37.4145 - accuracy: 0.3736
Epoch 3/150
455/455 [==============================] - 0s 156us/step - loss: 33.6682 - accuracy: 0.3736
Epoch 4/150
455/455 [==============================] - 0s 151us/step - loss: 29.9145 - accuracy: 0.3736
Epoch 5/150
455/455 [==============================] - 0s 185us/step - loss: 26.1384 - accuracy: 0.3736
Epoch 6/150
455/455 [==============================] - 0s 180us/step - loss: 22.3674 - accuracy: 0.3736
Epoch 7/150
455/455 [==============================] - 0s 174us/step - loss: 18.5490 - accuracy: 0.3736
Epoch 8/150
455/455 [==============================] - 0s 177us/step - loss: 14.7863 - accuracy: 0.3758
Epoch 9/150
455/455 [==============================] - 0s 169us/step - loss: 10.9943 - accuracy: 0.3802
Epoch 10/150
455/455 [==============================] - 0s 184us

In [10]:
test(
    model = Sequential([
        Dense(X.shape[1], input_dim=X.shape[1], activation='relu'),
        Dense(X.shape[1], activation='relu'),
        Dense(X.shape[1], activation='relu'),
        Dense(X.shape[1], activation='relu'),
        Dense(X.shape[1], activation='relu'),
        Dense(X.shape[1], activation='relu'),
        Dense(1, activation='sigmoid')
    ]),
    optimizer = Adam(lr=0.0001),
    loss = 'binary_crossentropy',
    metrics=['accuracy'],
    epochs=150,
    batch_size=10
)

Epoch 1/150
455/455 [==============================] - 0s 570us/step - loss: 10.4129 - accuracy: 0.3736
Epoch 2/150
455/455 [==============================] - 0s 192us/step - loss: 0.7771 - accuracy: 0.7495
Epoch 3/150
455/455 [==============================] - 0s 212us/step - loss: 0.3756 - accuracy: 0.8549
Epoch 4/150
455/455 [==============================] - 0s 178us/step - loss: 0.3238 - accuracy: 0.8879
Epoch 5/150
455/455 [==============================] - 0s 190us/step - loss: 0.3061 - accuracy: 0.8967
Epoch 6/150
455/455 [==============================] - 0s 199us/step - loss: 0.2897 - accuracy: 0.8879
Epoch 7/150
455/455 [==============================] - 0s 186us/step - loss: 0.2697 - accuracy: 0.9077
Epoch 8/150
455/455 [==============================] - 0s 191us/step - loss: 0.2663 - accuracy: 0.9099
Epoch 9/150
455/455 [==============================] - 0s 189us/step - loss: 0.2692 - accuracy: 0.9011
Epoch 10/150
455/455 [==============================] - 0s 194us/step - 

In [11]:
test(
    model = Sequential([
        Dense(X.shape[1], input_dim=X.shape[1], activation='relu'),
        Dense(X.shape[1], activation='relu'),
        Dense(X.shape[1], activation='relu'),
        Dense(X.shape[1], activation='relu'),
        Dense(X.shape[1], activation='relu'),
        Dense(X.shape[1], activation='relu'),
        Dense(1, activation='sigmoid')
    ]),
    optimizer = Adam(lr=0.0001),
    loss = 'binary_crossentropy',
    metrics=['accuracy'],
    epochs=150,
    batch_size=5
)

Epoch 1/150
455/455 [==============================] - 0s 721us/step - loss: 0.9323 - accuracy: 0.5033
Epoch 2/150
455/455 [==============================] - 0s 315us/step - loss: 0.3554 - accuracy: 0.8813
Epoch 3/150
455/455 [==============================] - 0s 306us/step - loss: 0.2605 - accuracy: 0.9253
Epoch 4/150
455/455 [==============================] - 0s 313us/step - loss: 0.2313 - accuracy: 0.9231
Epoch 5/150
455/455 [==============================] - 0s 306us/step - loss: 0.2252 - accuracy: 0.9209
Epoch 6/150
455/455 [==============================] - 0s 407us/step - loss: 0.2376 - accuracy: 0.9077
Epoch 7/150
455/455 [==============================] - 0s 466us/step - loss: 0.2204 - accuracy: 0.9209
Epoch 8/150
455/455 [==============================] - 0s 379us/step - loss: 0.2173 - accuracy: 0.9165
Epoch 9/150
455/455 [==============================] - 0s 374us/step - loss: 0.2115 - accuracy: 0.9319
Epoch 10/150
455/455 [==============================] - 0s 398us/step - l

In [12]:
test(
    model = Sequential([
        Dense(X.shape[1], input_dim=X.shape[1], activation='relu'),
        Dense(X.shape[1], activation='relu'),
        Dense(X.shape[1], activation='relu'),
        Dense(X.shape[1], activation='relu'),
        Dense(X.shape[1], activation='relu'),
        Dense(X.shape[1], activation='relu'),
        Dense(1, activation='sigmoid')
    ]),
    optimizer = Adam(lr=0.0001),
    loss = 'binary_crossentropy',
    metrics=['accuracy'],
    epochs=150,
    batch_size=20
)

Epoch 1/150
455/455 [==============================] - 0s 479us/step - loss: 22.9177 - accuracy: 0.3736
Epoch 2/150
455/455 [==============================] - 0s 126us/step - loss: 13.0540 - accuracy: 0.3736
Epoch 3/150
455/455 [==============================] - 0s 213us/step - loss: 5.1529 - accuracy: 0.3736
Epoch 4/150
455/455 [==============================] - 0s 227us/step - loss: 0.7801 - accuracy: 0.6637
Epoch 5/150
455/455 [==============================] - 0s 134us/step - loss: 0.4898 - accuracy: 0.8154
Epoch 6/150
455/455 [==============================] - 0s 199us/step - loss: 0.4085 - accuracy: 0.8505
Epoch 7/150
455/455 [==============================] - 0s 147us/step - loss: 0.3409 - accuracy: 0.9055
Epoch 8/150
455/455 [==============================] - 0s 154us/step - loss: 0.3018 - accuracy: 0.8901
Epoch 9/150
455/455 [==============================] - 0s 179us/step - loss: 0.2951 - accuracy: 0.9011
Epoch 10/150
455/455 [==============================] - 0s 140us/step -

In [13]:
test(
    model = Sequential([
        Dense(X.shape[1], input_dim=X.shape[1], activation='relu'),
        Dense(X.shape[1], activation='relu'),
        Dense(X.shape[1], activation='relu'),
        Dense(X.shape[1], activation='relu'),
        Dense(X.shape[1], activation='relu'),
        Dense(X.shape[1], activation='relu'),
        Dense(1, activation='sigmoid')
    ]),
    optimizer = Adam(lr=0.0001),
    loss = 'binary_crossentropy',
    metrics=['accuracy'],
    epochs=150,
    batch_size=50
)

Epoch 1/150
455/455 [==============================] - 0s 447us/step - loss: 3.4963 - accuracy: 0.6264
Epoch 2/150
455/455 [==============================] - 0s 49us/step - loss: 0.7811 - accuracy: 0.4747
Epoch 3/150
455/455 [==============================] - 0s 54us/step - loss: 0.7903 - accuracy: 0.3736
Epoch 4/150
455/455 [==============================] - 0s 61us/step - loss: 0.6124 - accuracy: 0.6791
Epoch 5/150
455/455 [==============================] - 0s 86us/step - loss: 0.5595 - accuracy: 0.8352
Epoch 6/150
455/455 [==============================] - 0s 82us/step - loss: 0.5406 - accuracy: 0.8615
Epoch 7/150
455/455 [==============================] - 0s 105us/step - loss: 0.5344 - accuracy: 0.8505
Epoch 8/150
455/455 [==============================] - 0s 102us/step - loss: 0.5204 - accuracy: 0.8703
Epoch 9/150
455/455 [==============================] - 0s 100us/step - loss: 0.5132 - accuracy: 0.8725
Epoch 10/150
455/455 [==============================] - 0s 104us/step - loss: 

In [14]:
test(
    model = Sequential([
        Dense(X.shape[1], input_dim=X.shape[1], activation='relu'),
        Dense(X.shape[1], activation='relu'),
        Dense(X.shape[1], activation='relu'),
        Dense(X.shape[1], activation='relu'),
        Dense(X.shape[1], activation='relu'),
        Dense(X.shape[1], activation='relu'),
        Dense(1, activation='sigmoid')
    ]),
    optimizer = SGD(lr=0.0001),
    loss = 'binary_crossentropy',
    metrics=['accuracy'],
    epochs=150,
    batch_size=10
)

Epoch 1/150
455/455 [==============================] - 0s 363us/step - loss: 1.1618 - accuracy: 0.6220
Epoch 2/150
455/455 [==============================] - 0s 198us/step - loss: 0.4901 - accuracy: 0.8396
Epoch 3/150
455/455 [==============================] - 0s 180us/step - loss: 0.4420 - accuracy: 0.8198
Epoch 4/150
455/455 [==============================] - 0s 194us/step - loss: 0.3589 - accuracy: 0.8725
Epoch 5/150
455/455 [==============================] - 0s 244us/step - loss: 0.4036 - accuracy: 0.8571
Epoch 6/150
455/455 [==============================] - 0s 223us/step - loss: 0.3842 - accuracy: 0.8308
Epoch 7/150
455/455 [==============================] - 0s 212us/step - loss: 0.3659 - accuracy: 0.8593
Epoch 8/150
455/455 [==============================] - 0s 219us/step - loss: 0.4432 - accuracy: 0.8154
Epoch 9/150
455/455 [==============================] - 0s 251us/step - loss: 0.3506 - accuracy: 0.8505
Epoch 10/150
455/455 [==============================] - 0s 240us/step - l

## Регрессия

In [15]:
data = load_boston()
X = data.data
y = data.target
print(y[:10])

[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9]


In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True, random_state=7)

In [17]:
test(
    model = Sequential([
        Dense(12, input_dim=X.shape[1], activation='relu'),
        Dense(8, activation='relu'),
        # для регрессии активация не нужна
        Dense(1)
    ]),
    optimizer = Adam(lr=0.00001),
    # для регрессии нужно указать MSE/MAE (или другие активации)
    loss='mean_squared_error',
    metrics=['mean_absolute_percentage_error'],
    epochs=150,
    batch_size=10
)

Epoch 1/150
404/404 [==============================] - 0s 287us/step - loss: 70150.2472 - mean_absolute_percentage_error: 1409.3668
Epoch 2/150
404/404 [==============================] - 0s 120us/step - loss: 68686.9101 - mean_absolute_percentage_error: 1393.9977
Epoch 3/150
404/404 [==============================] - 0s 102us/step - loss: 67258.2177 - mean_absolute_percentage_error: 1378.9773
Epoch 4/150
404/404 [==============================] - 0s 154us/step - loss: 65853.7967 - mean_absolute_percentage_error: 1364.1569
Epoch 5/150
404/404 [==============================] - 0s 179us/step - loss: 64459.3373 - mean_absolute_percentage_error: 1349.1794
Epoch 6/150
404/404 [==============================] - 0s 201us/step - loss: 63079.0699 - mean_absolute_percentage_error: 1334.3306
Epoch 7/150
404/404 [==============================] - 0s 206us/step - loss: 61733.4815 - mean_absolute_percentage_error: 1319.5664
Epoch 8/150
404/404 [==============================] - 0s 187us/step - loss:

404/404 [==============================] - 0s 105us/step - loss: 1424.6412 - mean_absolute_percentage_error: 189.5116
Epoch 125/150
404/404 [==============================] - 0s 114us/step - loss: 1364.4399 - mean_absolute_percentage_error: 185.0923
Epoch 126/150
404/404 [==============================] - 0s 108us/step - loss: 1307.3476 - mean_absolute_percentage_error: 180.9847
Epoch 127/150
404/404 [==============================] - 0s 100us/step - loss: 1253.3568 - mean_absolute_percentage_error: 177.0260
Epoch 128/150
404/404 [==============================] - 0s 111us/step - loss: 1202.1934 - mean_absolute_percentage_error: 173.2258
Epoch 129/150
404/404 [==============================] - 0s 116us/step - loss: 1153.1255 - mean_absolute_percentage_error: 169.3815
Epoch 130/150
404/404 [==============================] - 0s 112us/step - loss: 1107.1747 - mean_absolute_percentage_error: 165.6807
Epoch 131/150
404/404 [==============================] - 0s 89us/step - loss: 1063.5373 - 

In [18]:
test(
    model = Sequential([
        Dense(X.shape[1], input_dim=X.shape[1], activation='relu'),
        Dense(X.shape[1], activation='relu'),
        Dense(1)
    ]),
    optimizer = Adam(lr=0.00001),
    loss='mean_squared_error',
    metrics=['mean_absolute_percentage_error'],
    epochs=150,
    batch_size=10
)

Epoch 1/150
404/404 [==============================] - 0s 300us/step - loss: 1373.4385 - mean_absolute_percentage_error: 176.5028
Epoch 2/150
404/404 [==============================] - 0s 121us/step - loss: 1327.1958 - mean_absolute_percentage_error: 173.1391
Epoch 3/150
404/404 [==============================] - 0s 124us/step - loss: 1284.5020 - mean_absolute_percentage_error: 170.1718
Epoch 4/150
404/404 [==============================] - 0s 140us/step - loss: 1244.6469 - mean_absolute_percentage_error: 167.1416
Epoch 5/150
404/404 [==============================] - 0s 141us/step - loss: 1207.8025 - mean_absolute_percentage_error: 164.4544
Epoch 6/150
404/404 [==============================] - 0s 98us/step - loss: 1175.4326 - mean_absolute_percentage_error: 162.0135
Epoch 7/150
404/404 [==============================] - 0s 115us/step - loss: 1145.4458 - mean_absolute_percentage_error: 159.6218
Epoch 8/150
404/404 [==============================] - 0s 157us/step - loss: 1118.1103 - me

404/404 [==============================] - 0s 93us/step - loss: 229.8618 - mean_absolute_percentage_error: 59.9679
Epoch 127/150
404/404 [==============================] - 0s 121us/step - loss: 227.1380 - mean_absolute_percentage_error: 59.4904
Epoch 128/150
404/404 [==============================] - 0s 107us/step - loss: 224.4828 - mean_absolute_percentage_error: 59.1001
Epoch 129/150
404/404 [==============================] - 0s 104us/step - loss: 221.7945 - mean_absolute_percentage_error: 58.6697
Epoch 130/150
404/404 [==============================] - 0s 139us/step - loss: 219.1387 - mean_absolute_percentage_error: 58.3113
Epoch 131/150
404/404 [==============================] - 0s 110us/step - loss: 216.5605 - mean_absolute_percentage_error: 57.8316
Epoch 132/150
404/404 [==============================] - 0s 117us/step - loss: 214.0020 - mean_absolute_percentage_error: 57.4109
Epoch 133/150
404/404 [==============================] - 0s 112us/step - loss: 211.4444 - mean_absolute_p

In [19]:
test(
    model = Sequential([
        Dense(X.shape[1], input_dim=X.shape[1], activation='relu'),
        Dropout(0.1),
        Dense(X.shape[1], activation='relu'),
        Dense(1)
    ]),
    optimizer = Adam(lr=0.00001),
    loss='mean_squared_error',
    metrics=['mean_absolute_percentage_error'],
    epochs=150,
    batch_size=10
)

Epoch 1/150
404/404 [==============================] - 0s 347us/step - loss: 3683.3905 - mean_absolute_percentage_error: 298.5612
Epoch 2/150
404/404 [==============================] - 0s 139us/step - loss: 3448.9482 - mean_absolute_percentage_error: 288.5149
Epoch 3/150
404/404 [==============================] - 0s 147us/step - loss: 3373.4285 - mean_absolute_percentage_error: 284.4000
Epoch 4/150
404/404 [==============================] - 0s 117us/step - loss: 3355.4614 - mean_absolute_percentage_error: 280.4982
Epoch 5/150
404/404 [==============================] - 0s 157us/step - loss: 3102.1767 - mean_absolute_percentage_error: 271.0968
Epoch 6/150
404/404 [==============================] - 0s 129us/step - loss: 3179.6135 - mean_absolute_percentage_error: 277.5216
Epoch 7/150
404/404 [==============================] - 0s 127us/step - loss: 3209.2155 - mean_absolute_percentage_error: 278.3617
Epoch 8/150
404/404 [==============================] - 0s 146us/step - loss: 3209.0990 - m

404/404 [==============================] - 0s 113us/step - loss: 327.6792 - mean_absolute_percentage_error: 78.3540
Epoch 127/150
404/404 [==============================] - 0s 96us/step - loss: 287.0580 - mean_absolute_percentage_error: 71.4633
Epoch 128/150
404/404 [==============================] - 0s 104us/step - loss: 280.0809 - mean_absolute_percentage_error: 73.1054
Epoch 129/150
404/404 [==============================] - 0s 108us/step - loss: 296.2514 - mean_absolute_percentage_error: 73.0169
Epoch 130/150
404/404 [==============================] - 0s 101us/step - loss: 296.3258 - mean_absolute_percentage_error: 74.0389
Epoch 131/150
404/404 [==============================] - 0s 107us/step - loss: 312.8762 - mean_absolute_percentage_error: 74.2244
Epoch 132/150
404/404 [==============================] - 0s 98us/step - loss: 333.0893 - mean_absolute_percentage_error: 77.0195
Epoch 133/150
404/404 [==============================] - 0s 114us/step - loss: 280.0797 - mean_absolute_pe

In [20]:
test(
    model = Sequential([
        Dense(X.shape[1], input_dim=X.shape[1], activation='relu'),
        Dropout(0.1),
        Dense(X.shape[1], activation='relu'),
        Dropout(0.1),
        Dense(X.shape[1], activation='relu'),
        Dropout(0.1),
        Dense(X.shape[1], activation='relu'),
        Dense(1)
    ]),
    optimizer = Adam(lr=0.01),
    loss='mean_squared_error',
    metrics=['mean_absolute_percentage_error'],
    epochs=150,
    batch_size=10
)

Epoch 1/150
404/404 [==============================] - 0s 693us/step - loss: 177.5988 - mean_absolute_percentage_error: 50.9308
Epoch 2/150
404/404 [==============================] - 0s 232us/step - loss: 97.7733 - mean_absolute_percentage_error: 36.6306
Epoch 3/150
404/404 [==============================] - 0s 196us/step - loss: 80.0228 - mean_absolute_percentage_error: 31.3121
Epoch 4/150
404/404 [==============================] - 0s 205us/step - loss: 85.1725 - mean_absolute_percentage_error: 32.6869
Epoch 5/150
404/404 [==============================] - 0s 198us/step - loss: 73.5006 - mean_absolute_percentage_error: 30.0896
Epoch 6/150
404/404 [==============================] - 0s 185us/step - loss: 71.6404 - mean_absolute_percentage_error: 29.6289
Epoch 7/150
404/404 [==============================] - 0s 181us/step - loss: 71.1268 - mean_absolute_percentage_error: 29.3982
Epoch 8/150
404/404 [==============================] - 0s 166us/step - loss: 72.9646 - mean_absolute_percentag

404/404 [==============================] - 0s 120us/step - loss: 25.0188 - mean_absolute_percentage_error: 19.4088
Epoch 66/150
404/404 [==============================] - 0s 130us/step - loss: 24.1404 - mean_absolute_percentage_error: 19.3324
Epoch 67/150
404/404 [==============================] - 0s 139us/step - loss: 25.9024 - mean_absolute_percentage_error: 19.4111
Epoch 68/150
404/404 [==============================] - 0s 126us/step - loss: 25.6341 - mean_absolute_percentage_error: 18.7798
Epoch 69/150
404/404 [==============================] - 0s 167us/step - loss: 23.1760 - mean_absolute_percentage_error: 18.5716
Epoch 70/150
404/404 [==============================] - 0s 155us/step - loss: 23.2354 - mean_absolute_percentage_error: 18.3935
Epoch 71/150
404/404 [==============================] - 0s 157us/step - loss: 40.5414 - mean_absolute_percentage_error: 23.4186
Epoch 72/150
404/404 [==============================] - 0s 145us/step - loss: 31.3590 - mean_absolute_percentage_erro

In [21]:
test(
    model = Sequential([
        Dense(X.shape[1], input_dim=X.shape[1], activation='relu'),
        Dropout(0.1),
        Dense(X.shape[1], activation='relu'),
        Dropout(0.1),
        Dense(X.shape[1], activation='relu'),
        Dropout(0.1),
        Dense(X.shape[1], activation='relu'),
        Dense(1)
    ]),
    optimizer = Adam(lr=0.01),
    loss='mean_squared_error',
    metrics=['mean_absolute_percentage_error'],
    epochs=150,
    batch_size=20
)

Epoch 1/150
404/404 [==============================] - 0s 909us/step - loss: 479.0761 - mean_absolute_percentage_error: 75.8364
Epoch 2/150
404/404 [==============================] - 0s 171us/step - loss: 148.9261 - mean_absolute_percentage_error: 44.9778
Epoch 3/150
404/404 [==============================] - 0s 213us/step - loss: 112.8976 - mean_absolute_percentage_error: 36.9388
Epoch 4/150
404/404 [==============================] - 0s 189us/step - loss: 88.9384 - mean_absolute_percentage_error: 32.6697
Epoch 5/150
404/404 [==============================] - 0s 208us/step - loss: 93.4909 - mean_absolute_percentage_error: 35.3544
Epoch 6/150
404/404 [==============================] - 0s 204us/step - loss: 82.1941 - mean_absolute_percentage_error: 32.0326
Epoch 7/150
404/404 [==============================] - 0s 138us/step - loss: 86.1676 - mean_absolute_percentage_error: 33.4132
Epoch 8/150
404/404 [==============================] - 0s 97us/step - loss: 89.2138 - mean_absolute_percenta

404/404 [==============================] - 0s 83us/step - loss: 29.0256 - mean_absolute_percentage_error: 18.7298
Epoch 130/150
404/404 [==============================] - 0s 85us/step - loss: 31.1158 - mean_absolute_percentage_error: 19.7087
Epoch 131/150
404/404 [==============================] - 0s 74us/step - loss: 21.6292 - mean_absolute_percentage_error: 17.6602
Epoch 132/150
404/404 [==============================] - 0s 77us/step - loss: 31.6396 - mean_absolute_percentage_error: 19.3651
Epoch 133/150
404/404 [==============================] - 0s 81us/step - loss: 24.3058 - mean_absolute_percentage_error: 17.8096
Epoch 134/150
404/404 [==============================] - 0s 98us/step - loss: 23.8095 - mean_absolute_percentage_error: 16.7101
Epoch 135/150
404/404 [==============================] - 0s 92us/step - loss: 24.0265 - mean_absolute_percentage_error: 16.9820
Epoch 136/150
404/404 [==============================] - 0s 83us/step - loss: 23.7997 - mean_absolute_percentage_error

In [22]:
test(
    model = Sequential([
        Dense(X.shape[1], input_dim=X.shape[1], activation='relu'),
        Dropout(0.1),
        Dense(X.shape[1], activation='relu'),
        Dropout(0.1),
        Dense(X.shape[1], activation='relu'),
        Dropout(0.1),
        Dense(X.shape[1], activation='relu'),
        Dense(1)
    ]),
    optimizer = Adam(lr=0.01),
    loss='mean_absolute_error',
    metrics=['mean_absolute_percentage_error'],
    epochs=150,
    batch_size=10
)

Epoch 1/150
404/404 [==============================] - 0s 584us/step - loss: 11.3284 - mean_absolute_percentage_error: 55.3664
Epoch 2/150
404/404 [==============================] - 0s 176us/step - loss: 7.4409 - mean_absolute_percentage_error: 34.1291
Epoch 3/150
404/404 [==============================] - 0s 171us/step - loss: 7.1535 - mean_absolute_percentage_error: 33.4976
Epoch 4/150
404/404 [==============================] - 0s 152us/step - loss: 5.9319 - mean_absolute_percentage_error: 26.3359
Epoch 5/150
404/404 [==============================] - 0s 171us/step - loss: 6.4752 - mean_absolute_percentage_error: 28.4025
Epoch 6/150
404/404 [==============================] - 0s 262us/step - loss: 6.5033 - mean_absolute_percentage_error: 29.2011
Epoch 7/150
404/404 [==============================] - 0s 244us/step - loss: 6.8543 - mean_absolute_percentage_error: 31.6723
Epoch 8/150
404/404 [==============================] - 0s 214us/step - loss: 6.3964 - mean_absolute_percentage_error:

404/404 [==============================] - 0s 168us/step - loss: 4.7944 - mean_absolute_percentage_error: 23.4132
Epoch 130/150
404/404 [==============================] - 0s 147us/step - loss: 3.8522 - mean_absolute_percentage_error: 19.0771
Epoch 131/150
404/404 [==============================] - 0s 137us/step - loss: 4.0812 - mean_absolute_percentage_error: 19.2527
Epoch 132/150
404/404 [==============================] - 0s 133us/step - loss: 3.9208 - mean_absolute_percentage_error: 18.7567
Epoch 133/150
404/404 [==============================] - 0s 136us/step - loss: 3.6010 - mean_absolute_percentage_error: 18.4695
Epoch 134/150
404/404 [==============================] - 0s 145us/step - loss: 3.6159 - mean_absolute_percentage_error: 18.5479
Epoch 135/150
404/404 [==============================] - 0s 144us/step - loss: 4.4144 - mean_absolute_percentage_error: 20.7386
Epoch 136/150
404/404 [==============================] - 0s 128us/step - loss: 4.2484 - mean_absolute_percentage_error

In [23]:
test(
    model = Sequential([
        Dense(X.shape[1], input_dim=X.shape[1], activation='relu'),
        Dropout(0.1),
        Dense(X.shape[1], activation='relu'),
        Dropout(0.1),
        Dense(X.shape[1], activation='relu'),
        Dropout(0.1),
        Dense(X.shape[1], activation='relu'),
        Dense(1)
    ]),
    optimizer = Adam(lr=0.01),
    loss='mean_squared_logarithmic_error',
    metrics=['mean_absolute_percentage_error'],
    epochs=150,
    batch_size=10
)

Epoch 1/150
404/404 [==============================] - 0s 940us/step - loss: 0.5005 - mean_absolute_percentage_error: 74.5723
Epoch 2/150
404/404 [==============================] - 0s 221us/step - loss: 0.3140 - mean_absolute_percentage_error: 49.6379
Epoch 3/150
404/404 [==============================] - 0s 202us/step - loss: 0.2562 - mean_absolute_percentage_error: 45.9949
Epoch 4/150
404/404 [==============================] - 0s 214us/step - loss: 0.1873 - mean_absolute_percentage_error: 35.4682
Epoch 5/150
404/404 [==============================] - 0s 326us/step - loss: 0.1636 - mean_absolute_percentage_error: 34.4050
Epoch 6/150
404/404 [==============================] - 0s 220us/step - loss: 0.1508 - mean_absolute_percentage_error: 32.1015
Epoch 7/150
404/404 [==============================] - 0s 176us/step - loss: 0.1458 - mean_absolute_percentage_error: 30.7307
Epoch 8/150
404/404 [==============================] - 0s 219us/step - loss: 0.1392 - mean_absolute_percentage_error: 

404/404 [==============================] - 0s 170us/step - loss: 0.0567 - mean_absolute_percentage_error: 19.4664
Epoch 130/150
404/404 [==============================] - 0s 151us/step - loss: 0.0583 - mean_absolute_percentage_error: 19.0329
Epoch 131/150
404/404 [==============================] - 0s 142us/step - loss: 0.0541 - mean_absolute_percentage_error: 19.3404
Epoch 132/150
404/404 [==============================] - 0s 150us/step - loss: 0.0529 - mean_absolute_percentage_error: 19.1070
Epoch 133/150
404/404 [==============================] - 0s 143us/step - loss: 0.0546 - mean_absolute_percentage_error: 19.8924
Epoch 134/150
404/404 [==============================] - 0s 147us/step - loss: 0.0546 - mean_absolute_percentage_error: 18.7016
Epoch 135/150
404/404 [==============================] - 0s 140us/step - loss: 0.0576 - mean_absolute_percentage_error: 19.6090
Epoch 136/150
404/404 [==============================] - 0s 152us/step - loss: 0.0541 - mean_absolute_percentage_error

In [24]:
test(
    model = Sequential([
        Dense(X.shape[1], input_dim=X.shape[1], activation='relu'),
        Dropout(0.1),
        Dense(X.shape[1], activation='relu'),
        Dropout(0.1),
        Dense(X.shape[1], activation='relu'),
        Dropout(0.1),
        Dense(X.shape[1], activation='relu'),
        Dense(1)
    ]),
    optimizer = Adam(lr=0.01),
    loss='mean_absolute_percentage_error',
    metrics=['mean_absolute_percentage_error'],
    epochs=150,
    batch_size=10
)

Epoch 1/150
404/404 [==============================] - 0s 795us/step - loss: 55.6687 - mean_absolute_percentage_error: 55.6687
Epoch 2/150
404/404 [==============================] - 0s 178us/step - loss: 37.8909 - mean_absolute_percentage_error: 37.8909
Epoch 3/150
404/404 [==============================] - 0s 164us/step - loss: 30.3424 - mean_absolute_percentage_error: 30.3424
Epoch 4/150
404/404 [==============================] - 0s 194us/step - loss: 28.2090 - mean_absolute_percentage_error: 28.2090
Epoch 5/150
404/404 [==============================] - 0s 185us/step - loss: 29.3808 - mean_absolute_percentage_error: 29.3808
Epoch 6/150
404/404 [==============================] - 0s 190us/step - loss: 27.8379 - mean_absolute_percentage_error: 27.8379
Epoch 7/150
404/404 [==============================] - 0s 164us/step - loss: 28.5305 - mean_absolute_percentage_error: 28.5305
Epoch 8/150
404/404 [==============================] - 0s 164us/step - loss: 25.8735 - mean_absolute_percentage

404/404 [==============================] - 0s 150us/step - loss: 19.3307 - mean_absolute_percentage_error: 19.3307
Epoch 66/150
404/404 [==============================] - 0s 144us/step - loss: 19.2802 - mean_absolute_percentage_error: 19.2802
Epoch 67/150
404/404 [==============================] - 0s 148us/step - loss: 18.4188 - mean_absolute_percentage_error: 18.4188
Epoch 68/150
404/404 [==============================] - 0s 143us/step - loss: 18.0425 - mean_absolute_percentage_error: 18.0425
Epoch 69/150
404/404 [==============================] - 0s 141us/step - loss: 17.3860 - mean_absolute_percentage_error: 17.3860
Epoch 70/150
404/404 [==============================] - 0s 151us/step - loss: 18.1811 - mean_absolute_percentage_error: 18.1811
Epoch 71/150
404/404 [==============================] - 0s 146us/step - loss: 19.4587 - mean_absolute_percentage_error: 19.4587
Epoch 72/150
404/404 [==============================] - 0s 149us/step - loss: 19.4754 - mean_absolute_percentage_erro

/home/nikolai/Projects/MIPT-ML-Fall-2019/env/lib/python3.7/site-packages/keras/callbacks/callbacks.py:95: RuntimeWarning: Method (on_train_batch_end) is slow compared to the batch update (0.234395). Check your callbacks.
  % (hook_name, delta_t_median), RuntimeWarning)
/home/nikolai/Projects/MIPT-ML-Fall-2019/env/lib/python3.7/site-packages/keras/callbacks/callbacks.py:95: RuntimeWarning: Method (on_train_batch_end) is slow compared to the batch update (0.117669). Check your callbacks.
  % (hook_name, delta_t_median), RuntimeWarning)


404/404 [==============================] - 0s 169us/step - loss: 17.4735 - mean_absolute_percentage_error: 17.4735
Epoch 137/150
404/404 [==============================] - 0s 152us/step - loss: 19.6409 - mean_absolute_percentage_error: 19.6409
Epoch 138/150
404/404 [==============================] - 0s 122us/step - loss: 17.1576 - mean_absolute_percentage_error: 17.1576
Epoch 139/150
404/404 [==============================] - 0s 124us/step - loss: 17.1789 - mean_absolute_percentage_error: 17.1789
Epoch 140/150
404/404 [==============================] - 0s 125us/step - loss: 18.2649 - mean_absolute_percentage_error: 18.2649
Epoch 141/150
404/404 [==============================] - 0s 143us/step - loss: 17.3425 - mean_absolute_percentage_error: 17.3425
Epoch 142/150
404/404 [==============================] - 0s 129us/step - loss: 16.5919 - mean_absolute_percentage_error: 16.5919
Epoch 143/150
404/404 [==============================] - 0s 118us/step - loss: 18.2216 - mean_absolute_percenta

## Многоклассовая классификация

In [25]:
data = load_iris()
X = data.data
y = data.target
y = np_utils.to_categorical(y)
print(y[:10])

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, shuffle=True, random_state=7)

In [27]:
test(
    model = Sequential([
        Dense(12, input_dim=X.shape[1], activation='relu'),
        Dense(8, activation='relu'),
        # для многоклассовой классификации на выходе l нейронов и софтмакс
        Dense(3, activation='softmax')
    ]),
    optimizer = Adam(lr=0.00001),
    # для многоклассовой классификации
    loss = 'categorical_crossentropy',
    metrics=['accuracy'],
    epochs=150,
    batch_size=10
)

Epoch 1/150
120/120 [==============================] - 0s 709us/step - loss: 1.5837 - accuracy: 0.3333
Epoch 2/150
120/120 [==============================] - 0s 116us/step - loss: 1.5815 - accuracy: 0.3333
Epoch 3/150
120/120 [==============================] - 0s 141us/step - loss: 1.5794 - accuracy: 0.3333
Epoch 4/150
120/120 [==============================] - 0s 151us/step - loss: 1.5771 - accuracy: 0.3333
Epoch 5/150
120/120 [==============================] - 0s 146us/step - loss: 1.5750 - accuracy: 0.3333
Epoch 6/150
120/120 [==============================] - 0s 166us/step - loss: 1.5730 - accuracy: 0.3333
Epoch 7/150
120/120 [==============================] - 0s 171us/step - loss: 1.5707 - accuracy: 0.3333
Epoch 8/150
120/120 [==============================] - 0s 155us/step - loss: 1.5687 - accuracy: 0.3333
Epoch 9/150
120/120 [==============================] - 0s 207us/step - loss: 1.5666 - accuracy: 0.3333
Epoch 10/150
120/120 [==============================] - 0s 164us/step - l

In [28]:
test(
    model = Sequential([
        Dense(X.shape[1], input_dim=X.shape[1], activation='relu'),
        Dense(X.shape[1], activation='relu'),
        Dense(3, activation='softmax')
    ]),
    optimizer = Adam(lr=0.00001),
    loss = 'categorical_crossentropy',
    metrics=['accuracy'],
    epochs=150,
    batch_size=10
)

Epoch 1/150
120/120 [==============================] - 0s 622us/step - loss: 1.4695 - accuracy: 0.3333
Epoch 2/150
120/120 [==============================] - 0s 100us/step - loss: 1.4672 - accuracy: 0.3333
Epoch 3/150
120/120 [==============================] - 0s 127us/step - loss: 1.4649 - accuracy: 0.3333
Epoch 4/150
120/120 [==============================] - 0s 102us/step - loss: 1.4626 - accuracy: 0.3333
Epoch 5/150
120/120 [==============================] - 0s 130us/step - loss: 1.4603 - accuracy: 0.3333
Epoch 6/150
120/120 [==============================] - 0s 108us/step - loss: 1.4580 - accuracy: 0.3333
Epoch 7/150
120/120 [==============================] - 0s 155us/step - loss: 1.4557 - accuracy: 0.3333
Epoch 8/150
120/120 [==============================] - 0s 132us/step - loss: 1.4535 - accuracy: 0.3333
Epoch 9/150
120/120 [==============================] - 0s 143us/step - loss: 1.4512 - accuracy: 0.3333
Epoch 10/150
120/120 [==============================] - 0s 131us/step - l

In [29]:
test(
    model = Sequential([
        Dense(X.shape[1], input_dim=X.shape[1], activation='relu'),
        Dense(X.shape[1], activation='relu'),
        Dense(3, activation='softmax')
    ]),
    optimizer = Adam(lr=0.01),
    loss = 'categorical_crossentropy',
    metrics=['accuracy'],
    epochs=150,
    batch_size=10
)

Epoch 1/150
120/120 [==============================] - 0s 779us/step - loss: 2.5957 - accuracy: 0.3333
Epoch 2/150
120/120 [==============================] - 0s 186us/step - loss: 1.0974 - accuracy: 0.3333
Epoch 3/150
120/120 [==============================] - 0s 133us/step - loss: 0.9166 - accuracy: 0.5417
Epoch 4/150
120/120 [==============================] - 0s 180us/step - loss: 0.8825 - accuracy: 0.6667
Epoch 5/150
120/120 [==============================] - 0s 228us/step - loss: 0.8409 - accuracy: 0.6667
Epoch 6/150
120/120 [==============================] - 0s 282us/step - loss: 0.7862 - accuracy: 0.6667
Epoch 7/150
120/120 [==============================] - 0s 287us/step - loss: 0.7390 - accuracy: 0.6667
Epoch 8/150
120/120 [==============================] - 0s 338us/step - loss: 0.7005 - accuracy: 0.6750
Epoch 9/150
120/120 [==============================] - 0s 202us/step - loss: 0.6670 - accuracy: 0.6833
Epoch 10/150
120/120 [==============================] - 0s 279us/step - l